### PR TITLE
Add possibility to use custom workspace

### LINKED ISSUE #16: Deploy a specific directory within repository
**Describe your question**

Wondering if it is possible to make this action deploy from a specific directory which is being created by `npm` task. Say `build/plugin-slug`.

Based on [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun), if I changed the directory with `working-directory` keyword within workflow, would that work as expected?

### PR DESCRIPTION
**Pull request by tatsta**
### Description of the Change

Add a possibility to specify workspace folder as environment variable `WORKSPACE_DIR` in case the Wordpress artefact files are located in custom folder. If environment variable `WORKSPACE_DIR` is not set `GITHUB_WORKSPACE` variable (and path) will be used

### Alternate Designs
Tried to redefine `GITHUB_WORKSPACE` variable when passing it into the action, but that didn't work for me. 

### Benefits
The actions is more reusable in other use cases

### Verification Process
I tested on a fork with .distignore and .gitattributes, both seemed to work fine. 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by helen** [comment]
Hi @tatsta - thanks for sending this in. Is this to address #16?

**Comment by tatsta** [comment]
Hi! Yes, hopefully this could solve it

**Comment by Lewiscowles1986** [comment]
I have re-based this and slightly altered what was here @tatsta & @helen I'd appreciate 👀 or responses if you find time.

For me not having this is preventing me from having a release github action. I Could totally roll my own, but if #16 and this are anything to go by, the issue affects a lot of people.

Differences:

* I decided `.gitattributes` and other ignore files ***SHOULD*** continue to live in the root of the repository. For me this is not about obfuscation, but rather shipping only what is needed for Runtime in WP and the plugin directory.
* I decided the assets folder should also be relative to the root of the repository. This does not prevent people moving it, but it means they don't mentally need to resolve paths I hope.

Thanks to both.

**Comment by jeffpaul** [comment]
@iamdharmesh bumping back up for your review.

**Comment by iamdharmesh** [comment]
@jeffpaul This is already handled by Tung's PR https://github.com/10up/action-wordpress-plugin-deploy/pull/83. So, we can proceed with closing this. Please feel free to reopen if I missed anything or misunderstood anything here.

Thanks

**Pull request closed without merging**
